version: "3.7"
services:
  web-django:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'web-django'
    container_name: 'web-django'
    restart: always
    networks:
      - escola-api-network
    ports:
    - "8000:8000"
    expose:
      - "8000"
networks:
  escola-api-network:
    driver: bridge

volumes:
  web-django: